name: build-and-release

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@dd7556a6905c9e8fa54f9907194f55f887f5db0d # main
    needs: build
    if: "${{ success() && always() && ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions: {} # none, since we use a custom app
    with:
      environment-name: release
      replace-files: |
        package-lock.json
        package.json
      package-name: classicube-script
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
