name: publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read # for checkout

jobs:
  publish-vs-marketplace:
    runs-on: ubuntu-24.04
    environment:
      name: publish-vs-marketplace
      url: https://marketplace.visualstudio.com/items?itemName=SpiralP.classicube-script
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: npm install

      - name: Publish to Visual Studio Code Marketplace
        uses: HaaLeo/publish-vscode-extension@1b8df468b849f76a143b8c18bf0ffa2075398d12 # v2.1.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

  publish-openvsx:
    runs-on: ubuntu-24.04
    environment:
      name: publish-openvsx
      url: https://open-vsx.org/extension/SpiralP/classicube-script
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: npm install

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@1b8df468b849f76a143b8c18bf0ffa2075398d12 # v2.1.0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
